export const formdata = [
  {
    id: 1,
    inputTitle: "Event",
    labelTitle: "My event is called",
    inputType: "text",
    placeholder: "",
    required: true,
    value: "",
  },
  {
    id: 2,
    inputTitle: "Start",
    labelTitle: "It start at",
    inputType: "date",
    placeholder: "",
    required: true,
    value: "",
  },
  {
    id: 3,
    inputTitle: "End",
    labelTitle: "It ends at",
    inputType: "date",
    placeholder: "",
    required: "false",
    value: "",
  },
  {
    id: 4,
    inputTitle: "Location",
    labelTitle: "Its happening at",
    inputType: "text",
    placeholder: "Location",
    required: "false",
    value: "",
  },
  {
    id: 5,
    inputTitle: "URL",
    labelTitle: "Add a URL link",
    inputType: "url",
    placeholder: "URL",
    required: "false",
    value: "",
  },
  {
    id: 6,
    inputTitle: "Description",
    labelTitle: "Event Description",
    inputType: "text",
    placeholder: "",
    required: "false",
    value: "",
  },
];
